version: '2'

services:
  redis:
    image: nettoclaudio/rancher-cattle-redis-ha-redis:1.0.0-rancher1
    environment:
      DEBUG_MODE: ${debug_mode}
      REDIS_HA_MASTER_PASSWORD: ${redis_password}
      REDIS_HA_SENTINEL_MASTER_NAME: ${redis_sentinel_master_name}
    labels:
      io.rancher.container.pull_image: always

  sentinel:
    image: nettoclaudio/rancher-cattle-redis-ha-redis-sentinel:1.0.0-rancher1
    environment:
      DEBUG_MODE: ${debug_mode}
      REDIS_HA_SENTINEL_MASTER_NAME: ${redis_sentinel_master_name}
      REDIS_HA_SENTINEL_PASSWORD: ${redis_password}
      REDIS_HA_SENTINEL_QUORUM: ${redis_sentinel_quorum}
    labels:
      io.rancher.container.pull_image: always
    links:
      - redis